### ISSUE TITLE
Preview app doesn't fit on the screen 1366 x 768

### ISSUE THREAD

**Issue by HelloHumans13** [Auburn/FastNoiseLite#83]
I have checked all my display settings and everything is right. I can't even scroll or resize this app. 

![pic](https://user-images.githubusercontent.com/70482437/144260421-7a8306a8-7ea2-404f-ab33-367cd618b8a9.png)

**Comment by Auburn** [comment]
That region should be scrollable, probably a layout issue

**Comment by nekotogd** [comment]
Same here, app is unusable in native settings because I can't save any of the textures made.
Issue is probably related to High-DPI scaling issues.

I have a 1080p laptop monitor with 150% scaling
![image](https://user-images.githubusercontent.com/81257780/171039983-99678d48-991f-40ae-896c-c655b767b4a8.png)

FastNoiseLite application has no scroll:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/81257780/171040076-9ad0161c-d3c5-4b2e-b425-3026dfd3ac03.png">

After resized scaling:
![image](https://user-images.githubusercontent.com/81257780/171040116-79ce606e-2b27-43f7-b8cd-8790f16ab358.png)

Application is fully visible:
![image](https://user-images.githubusercontent.com/81257780/171040168-15f7ab51-ecb3-4e8a-ab8f-6f3e59ac944f.png)

**Comment by Photonic0** [comment]
has anyone been able to solve this yet? I'm trying to do it myself but I have no clue how to open the visual editor

**Comment by Auburn** [comment]
Fixed in [v1.1.0](https://github.com/Auburn/FastNoiseLite/releases/tag/v1.1.0) with new web app
