### ISSUE TITLE
FastNoiseLite GLSL Proposal

### ISSUE THREAD

**Issue by dotlogix** [Auburn/FastNoiseLite#98]
Hey there I just ported your awesome library to GLSL.
If you like you could check it out here:
[https://www.shadertoy.com/view/sttBz8](https://www.shadertoy.com/view/sttBz8)

If there is interest I could create a PR to include it here :)

**Comment by Auburn** [comment]
Looks great! Thanks for working on this. It would be great if you could PR it!

Only thing I noted when looking through the code quickly is you could probably change the implementation of the basic math utility functions like '_fnlFastMin' to use The native GLSL min/max/etc.. instead of the branching that is there currently

**Comment by dotlogix** [comment]
Created a PR #99
